#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Reload systemd daemon
    systemctl daemon-reload || true

    # Enable user timers globally (started on next user login)
    systemctl --global enable battery-monitor.timer || true
    systemctl --global enable diskspace-monitor.timer || true
fi

#DEBHELPER#

exit 0
